/*
 * NewJFrame.java
 *
 * Created on 2009/03/18, 0:13:53
 */
package org.sais.chocolat.analyzer;

import org.sais.chocolat.analyzer.data.CADeck;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

/**
 *
 * @author Romulus
 */
public class ResultFrame extends javax.swing.JFrame {

    ArrayList<Replay> mReplays;

    public ResultFrame(AnalyzeResult result) {
        initComponents();
        setIconImage(new ImageIcon(ReadInnerFile.getURL("chocolat2.jpg")).getImage());
        jTextArea1.setText(result.useDecks);
        jTextArea2.setText(result.meetDecks);
        jTextArea3.setText(result.meetPlayers);
        jTextArea4.setText(result.deckNames);
        jTextArea5.setText(result.characters);
        jTextArea6.setText(result.cards);
        jTextArea7.setText(result.cardsAnalyze);
        if (result.cards.length() < 2) {
            jTabbedPane1.remove(jScrollPane7);
            jTabbedPane1.remove(jScrollPane8);
        } else {
            jTextArea6.setLocation(0, 0);
            jTextArea6.setCaretPosition(0);
            jScrollPane7.setLocation(0, 0);
            jTextArea7.setLocation(0, 0);
            jTextArea7.setCaretPosition(0);
            jScrollPane8.setLocation(0, 0);
        }
        jTextArea1.setLocation(0, 0);
        jTextArea2.setLocation(0, 0);
        jTextArea3.setLocation(0, 0);
        jTextArea4.setLocation(0, 0);
        jTextArea5.setLocation(0, 0);
        jTextArea1.setCaretPosition(0);
        jTextArea2.setCaretPosition(0);
        jTextArea3.setCaretPosition(0);
        jTextArea4.setCaretPosition(0);
        jTextArea5.setCaretPosition(0);
        jScrollPane1.setLocation(0, 0);
        jScrollPane2.setLocation(0, 0);
        jScrollPane3.setLocation(0, 0);
        jScrollPane4.setLocation(0, 0);
        jScrollPane5.setLocation(0, 0);
        if (result.writeReplay) {
            SimpleDateFormat format = new SimpleDateFormat("yyyy/MM/dd ");
            DefaultListModel mod = new DefaultListModel();
            jList1.setCellRenderer(new MyCellRenderer());
            for (final Replay r : result.replays) {
                String disp = "";
                Calendar c = CADeck.convertToCalendar(r.file.getName());
                if (c == null) {
                    c = Calendar.getInstance();
                    c.setTimeInMillis(r.file.lastModified());
                }
                disp += format.format(c.getTime());
                disp += r.result + " " + r.firstlast + " T" + r.turn + " " + r.oppname + " " + r.mydeck + " " + r.oppdeck + " ";

                Color color;
                if (r.result == null) {
                    color = new Color(0xFFFFE0);
                } else if (r.result.endsWith("勝")) {
                    if (r.firstlast.equals("先")) {
                        color = new Color(210, 255, 210);
                    } else {
                        color = new Color(190, 255, 230);
                    }
                } else if (r.result.endsWith("敗")) {
                    if (r.firstlast.equals("先")) {
                        color = new Color(255, 190, 230);
                    } else {
                        color = new Color(255, 210, 210);
                    }
                } else {
                    color = new Color(0xFFFFE0);
                }

                mod.add(mod.getSize(), new ListItem(color, disp));
            }
            jList1.setModel(mod);
        } else {
            jTabbedPane1.remove(jScrollPane6);
        }
        mReplays = result.replays;

    }

    private void openReplay() {
        String path = mReplays.get(jList1.getSelectedIndex()).file.getAbsolutePath();
        try {
            Runtime.getRuntime().exec(StartupFrame.sEditor + " " + path);
        } catch (IOException ex) {
            Logger.getLogger(ResultFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chololat's Note Result");

        jTabbedPane1.setFont(new java.awt.Font("ＭＳ Ｐゴシック", 0, 12));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTabbedPane1.addTab("デッキ使用", jScrollPane1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jTabbedPane1.addTab("デッキ遭遇", jScrollPane2);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jTabbedPane1.addTab("相手集計", jScrollPane3);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        jTabbedPane1.addTab("デッキ名別", jScrollPane4);

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane5.setViewportView(jTextArea5);

        jTabbedPane1.addTab("キャラクター", jScrollPane5);

        jList1.setFont(new java.awt.Font("ＭＳ Ｐゴシック", 0, 12));
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jList1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jList1KeyTyped(evt);
            }
        });
        jScrollPane6.setViewportView(jList1);

        jTabbedPane1.addTab("リプレイリスト", jScrollPane6);

        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jScrollPane7.setViewportView(jTextArea6);

        jTabbedPane1.addTab("カード集計", jScrollPane7);

        jTextArea7.setColumns(20);
        jTextArea7.setRows(5);
        jScrollPane8.setViewportView(jTextArea7);

        jTabbedPane1.addTab("カード解析", jScrollPane8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyTyped

}//GEN-LAST:event_jList1KeyTyped

    private void jList1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            openReplay();
        }
}//GEN-LAST:event_jList1KeyReleased

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        if (evt.getClickCount() > 1) {
            openReplay();
        }
    }//GEN-LAST:event_jList1MouseClicked
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    // End of variables declaration//GEN-END:variables
}
