/*
 * StartupFrame.java
 *
 * Created on 2009/06/14, 19:14:52
 */
package org.sais.chocolat.analyzer;

import org.sais.chocolat.analyzer.data.AnalyzeParameter;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.SwingWorker;

/**
 *
 * @author Romulus
 */
public class StartupFrame extends javax.swing.JFrame {

    private String[] args;
    public static String sEditor = "notepad.exe";

    static {
        /*        try {
        System.setOut(new PrintStream(new FileOutputStream("message_play.log")));
        System.setErr(new PrintStream(new FileOutputStream("message_error.log")));
        } catch (FileNotFoundException ex) {
        Logger.getLogger(StartupFrame.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }

    public StartupFrame(String[] args) {
        initComponents();
        setIconImage(new ImageIcon(ReadInnerFile.getURL("chocolat1.jpg")).getImage());
        this.args = args;
    }

    private void exec() throws Exception {
        new AnalyzerLinker().execute();
    }

    private class AnalyzerLinker extends SwingWorker<Void, Void> implements ChocolatsAnalyzer.IAnalyzerCallback {

        private long mTimer = 0;

        @Override
        protected Void doInBackground() throws Exception {
            mTimer = System.currentTimeMillis();
            try {
                AnalyzeParameter param = new AnalyzeParameter(_deckfilter.getText().trim(), _decknamefilter.getText(),
                        _oppnamefilter.getText(), _oppdeckfilter.getText(), _writefile.isSelected(), _listreplay.isSelected(),
                        Double.parseDouble(_minsize.getText()), _from.getText(), _to.getText(),
                        _firsts.getText(), _lasts.getText(), _calccards.isSelected(), _listallcards.isSelected(),
                        _launchatelier.isSelected(), _addreverse.isSelected(), _startVer.getSelectedIndex(), _endVer.getSelectedIndex());
                ChocolatsAnalyzer analyzer = new ChocolatsAnalyzer();
                analyzer.setCallback(this);
                analyzer.exec(args, param, ".", true);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
            return null;
        }

        @Override
        public void setLinkTotal(int max) {
            _linkprogress.setMinimum(0);
            _linkprogress.setMaximum(max);
            _linkprogress.setValue(0);
            _linkprogress.setStringPainted(true);
            _linkprogress.setString("0 / " + max);
        }

        @Override
        public void setLinkProgress(int progress) {
            _linkprogress.setValue(progress);
            _linkprogress.setString(progress + " / " + _linkprogress.getMaximum());
            setProgress(progress / _linkprogress.getMaximum());
        }

        @Override
        protected void done() {
            setLinkProgress(_linkprogress.getMaximum());
            _linkprogress.setForeground(new Color(0x408F20));
            System.out.println("Total time " + (System.currentTimeMillis() - mTimer) + " ms.");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _deckfilter = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        _start = new javax.swing.JButton();
        _writefile = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        _decknamefilter = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        _oppnamefilter = new javax.swing.JTextField();
        _listreplay = new javax.swing.JCheckBox();
        _useeditor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        _oppdeckfilter = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        _minsize = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        _firsts = new javax.swing.JTextField();
        _lasts = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        _to = new javax.swing.JTextField();
        _from = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        _calccards = new javax.swing.JCheckBox();
        _listallcards = new javax.swing.JCheckBox();
        _launchatelier = new javax.swing.JCheckBox();
        _linkprogress = new javax.swing.JProgressBar();
        jLabel13 = new javax.swing.JLabel();
        _addreverse = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        _startVer = new javax.swing.JComboBox();
        _endVer = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/sais/chocolat/analyzer/Bundle"); // NOI18N
        setTitle(bundle.getString("StartupFrame.title")); // NOI18N

        _deckfilter.setFont(new java.awt.Font("ＭＳ Ｐゴシック", 0, 12)); // NOI18N
        _deckfilter.setText(bundle.getString("StartupFrame._deckfilter.text")); // NOI18N
        _deckfilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _deckfilterActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("ＭＳ Ｐゴシック", 0, 12)); // NOI18N
        jLabel1.setText(bundle.getString("StartupFrame.jLabel1.text")); // NOI18N

        _start.setFont(new java.awt.Font("ＭＳ Ｐゴシック", 0, 12)); // NOI18N
        _start.setText(bundle.getString("StartupFrame._start.text")); // NOI18N
        _start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _startActionPerformed(evt);
            }
        });

        _writefile.setFont(new java.awt.Font("ＭＳ Ｐゴシック", 0, 12)); // NOI18N
        _writefile.setText(bundle.getString("StartupFrame._writefile.text")); // NOI18N

        jLabel2.setFont(new java.awt.Font("ＭＳ Ｐゴシック", 0, 12)); // NOI18N
        jLabel2.setText(bundle.getString("StartupFrame.jLabel2.text")); // NOI18N

        _decknamefilter.setFont(new java.awt.Font("ＭＳ Ｐゴシック", 0, 12)); // NOI18N
        _decknamefilter.setText(bundle.getString("StartupFrame._decknamefilter.text")); // NOI18N

        jLabel3.setFont(new java.awt.Font("ＭＳ Ｐゴシック", 0, 12)); // NOI18N
        jLabel3.setText(bundle.getString("StartupFrame.jLabel3.text")); // NOI18N

        _oppnamefilter.setFont(new java.awt.Font("ＭＳ Ｐゴシック", 0, 12)); // NOI18N
        _oppnamefilter.setText(bundle.getString("StartupFrame._oppnamefilter.text")); // NOI18N

        _listreplay.setFont(new java.awt.Font("ＭＳ Ｐゴシック", 0, 12)); // NOI18N
        _listreplay.setText(bundle.getString("StartupFrame._listreplay.text")); // NOI18N

        _useeditor.setFont(new java.awt.Font("ＭＳ Ｐゴシック", 0, 12)); // NOI18N
        _useeditor.setText(bundle.getString("StartupFrame._useeditor.text")); // NOI18N
        _useeditor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _useeditorActionPerformed(evt);
            }
        });
        _useeditor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                _useeditorFocusLost(evt);
            }
        });
        _useeditor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                _useeditorPropertyChange(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("ＭＳ Ｐゴシック", 0, 12)); // NOI18N
        jLabel4.setText(bundle.getString("StartupFrame.jLabel4.text")); // NOI18N

        _oppdeckfilter.setFont(new java.awt.Font("ＭＳ Ｐゴシック", 0, 12)); // NOI18N
        _oppdeckfilter.setText(bundle.getString("StartupFrame._oppdeckfilter.text")); // NOI18N

        jLabel5.setFont(new java.awt.Font("ＭＳ Ｐゴシック", 0, 12)); // NOI18N
        jLabel5.setText(bundle.getString("StartupFrame.jLabel5.text")); // NOI18N

        _minsize.setFont(new java.awt.Font("ＭＳ Ｐゴシック", 0, 12)); // NOI18N
        _minsize.setText(bundle.getString("StartupFrame._minsize.text")); // NOI18N

        jLabel6.setFont(new java.awt.Font("ＭＳ Ｐゴシック", 0, 12)); // NOI18N
        jLabel6.setText(bundle.getString("StartupFrame.jLabel6.text")); // NOI18N

        jLabel7.setFont(new java.awt.Font("ＭＳ Ｐゴシック", 0, 12)); // NOI18N
        jLabel7.setText(bundle.getString("StartupFrame.jLabel7.text")); // NOI18N

        _firsts.setFont(new java.awt.Font("ＭＳ Ｐゴシック", 0, 12)); // NOI18N
        _firsts.setText(bundle.getString("StartupFrame._firsts.text")); // NOI18N

        _lasts.setFont(new java.awt.Font("ＭＳ Ｐゴシック", 0, 12)); // NOI18N
        _lasts.setText(bundle.getString("StartupFrame._lasts.text")); // NOI18N

        jLabel8.setFont(new java.awt.Font("ＭＳ Ｐゴシック", 0, 12)); // NOI18N
        jLabel8.setText(bundle.getString("StartupFrame.jLabel8.text")); // NOI18N

        jLabel9.setFont(new java.awt.Font("ＭＳ Ｐゴシック", 0, 12)); // NOI18N
        jLabel9.setText(bundle.getString("StartupFrame.jLabel9.text")); // NOI18N

        _to.setFont(new java.awt.Font("ＭＳ Ｐゴシック", 0, 12)); // NOI18N
        _to.setText(bundle.getString("StartupFrame._to.text")); // NOI18N

        _from.setFont(new java.awt.Font("ＭＳ Ｐゴシック", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("ＭＳ Ｐゴシック", 0, 12)); // NOI18N
        jLabel10.setText("から");

        jLabel11.setFont(new java.awt.Font("ＭＳ Ｐゴシック", 0, 12)); // NOI18N
        jLabel11.setText(bundle.getString("StartupFrame.jLabel11.text")); // NOI18N

        jLabel12.setFont(new java.awt.Font("ＭＳ Ｐゴシック", 0, 12)); // NOI18N
        jLabel12.setText(bundle.getString("StartupFrame.jLabel12.text")); // NOI18N

        _calccards.setFont(new java.awt.Font("ＭＳ Ｐゴシック", 0, 12)); // NOI18N
        _calccards.setText(bundle.getString("StartupFrame._calccards.text")); // NOI18N

        _listallcards.setFont(new java.awt.Font("ＭＳ Ｐゴシック", 0, 12)); // NOI18N
        _listallcards.setText(bundle.getString("StartupFrame._listallcards.text")); // NOI18N

        _launchatelier.setFont(new java.awt.Font("ＭＳ Ｐゴシック", 0, 12)); // NOI18N
        _launchatelier.setText(bundle.getString("StartupFrame._launchatelier.text")); // NOI18N

        jLabel13.setFont(new java.awt.Font("ＭＳ Ｐゴシック", 0, 12)); // NOI18N
        jLabel13.setText(bundle.getString("StartupFrame.jLabel13.text")); // NOI18N

        _addreverse.setFont(new java.awt.Font("ＭＳ Ｐゴシック", 0, 12)); // NOI18N
        _addreverse.setText(bundle.getString("StartupFrame._addreverse.text")); // NOI18N

        jPanel1.setLayout(new java.awt.GridLayout(2, 4));

        _startVer.setFont(new java.awt.Font("MS PGothic", 0, 15)); // NOI18N
        _startVer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "一幕", "二幕", "三幕", "四幕", "五幕", "六幕", "七幕", "八幕" }));

        _endVer.setFont(new java.awt.Font("MS PGothic", 0, 15)); // NOI18N
        _endVer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "八幕", "七幕", "六幕", "五幕", "四幕", "三幕", "二幕", "一幕", " " }));

        jLabel14.setFont(new java.awt.Font("MS PGothic", 0, 15)); // NOI18N
        jLabel14.setText(bundle.getString("StartupFrame.jLabel14.text")); // NOI18N

        jLabel15.setFont(new java.awt.Font("MS PGothic", 0, 15)); // NOI18N
        jLabel15.setText(bundle.getString("StartupFrame.jLabel15.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_writefile)
                            .addComponent(jLabel13)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(_launchatelier)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(_addreverse))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(_calccards)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(_listallcards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(_listreplay)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(_useeditor, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(_startVer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(_endVer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_linkprogress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(_oppnamefilter, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(_oppdeckfilter, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(_decknamefilter, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(_deckfilter, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(_start, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel12)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(_to, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel11))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(_from, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel10))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jLabel7))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(_lasts, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(_firsts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel9)
                                                        .addComponent(jLabel8))))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_minsize, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_deckfilter, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_start))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(_decknamefilter, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_oppnamefilter, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_from, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_to, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(_oppdeckfilter, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(_writefile))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_firsts, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_lasts, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_listreplay)
                    .addComponent(_useeditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_calccards)
                    .addComponent(_listallcards))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_launchatelier)
                    .addComponent(_addreverse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_startVer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(_endVer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_minsize, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_linkprogress, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName(bundle.getString("StartupFrame.AccessibleContext.accessibleName")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__startActionPerformed
        try {
            exec();
        } catch (Exception ex) {
            Logger.getLogger(StartupFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event__startActionPerformed

    private void _useeditorPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event__useeditorPropertyChange
    }//GEN-LAST:event__useeditorPropertyChange

    private void _useeditorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__useeditorActionPerformed
    }//GEN-LAST:event__useeditorActionPerformed

    private void _useeditorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event__useeditorFocusLost
        sEditor = _useeditor.getText();
        System.out.println(_useeditor.getText());
    }//GEN-LAST:event__useeditorFocusLost

    private void _deckfilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__deckfilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__deckfilterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(final String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new StartupFrame(args).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox _addreverse;
    private javax.swing.JCheckBox _calccards;
    private javax.swing.JTextField _deckfilter;
    private javax.swing.JTextField _decknamefilter;
    private javax.swing.JComboBox _endVer;
    private javax.swing.JTextField _firsts;
    private javax.swing.JTextField _from;
    private javax.swing.JTextField _lasts;
    private javax.swing.JCheckBox _launchatelier;
    private javax.swing.JProgressBar _linkprogress;
    private javax.swing.JCheckBox _listallcards;
    private javax.swing.JCheckBox _listreplay;
    private javax.swing.JTextField _minsize;
    private javax.swing.JTextField _oppdeckfilter;
    private javax.swing.JTextField _oppnamefilter;
    private javax.swing.JButton _start;
    private javax.swing.JComboBox _startVer;
    private javax.swing.JTextField _to;
    private javax.swing.JTextField _useeditor;
    private javax.swing.JCheckBox _writefile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
