/*
 * CardViewer.java
 *
 * Created on 2008/10/14, 22:47
 */
package org.sais.fantasyfesta.ui;

import java.io.File;
import java.util.Locale;
import javax.swing.ImageIcon;
import org.sais.fantasyfesta.card.CardInfo;
import org.sais.fantasyfesta.card.CardDatabase;
import org.sais.fantasyfesta.deck.DeckEditor;
import org.sais.fantasyfesta.tool.FTool;

/**
 *
 * @author  Romulus
 */
public class CardViewer extends javax.swing.JFrame {

    private static final int MODE_GAME = 0;
    private static final int MODE_DECKEDITOR = 1;

    private int mode;

    public CardViewer() {
        initComponents();
    }

    public void show(CardInfo info) {
        int cardNo = info.getCardNo();
        /* Issue for 99xx -> 90xx */
        if (cardNo / 100 == 99) {
            cardNo -= 900;
        }
        File dir = new File("icon");
        if (dir.exists()) {
            File f = new File(dir + "/" + cardNo + "big.jpg");
            if (f.exists()) {
                _icon.setIcon(new ImageIcon(f.getPath()));
                if (!CardDatabase.getPronunciation(cardNo).equals("")) {
                    this.setTitle(CardDatabase.getPronunciation(cardNo));
                } else {
                    this.setTitle("FFO Card Viewer");
                }

                StackTraceElement[] trs = Thread.currentThread().getStackTrace();
                if (trs[2].getClassName().equals(DeckEditor.class.getName())) {
                    // Deck editor
                    mode = MODE_DECKEDITOR;
                    int x = FTool.readIntegerConfig("cardviewer_deckeditor_x", 790);
                    int y = FTool.readIntegerConfig("cardviewer_deckeditor_y", 0);
                    this.setLocation(x, y);
                } else {
                    // Game
                    mode = MODE_GAME;
                    int x = FTool.readIntegerConfig("cardviewer_game_x", 0);
                    int y = FTool.readIntegerConfig("cardviewer_game_y", 0);
                    this.setLocation(x, y);
                }

                this.setVisible(true);
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _icon = new javax.swing.JLabel();

        setTitle("FFO Card Viewer");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                formComponentMoved(evt);
            }
        });

        _icon.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_icon, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_icon, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentMoved
        if (mode == MODE_DECKEDITOR) {
            // Deck editor
            FTool.updateConfig("cardviewer_deckeditor_x", evt.getComponent().getX());
            FTool.updateConfig("cardviewer_deckeditor_y", evt.getComponent().getY());
        } else {
            // Game
            FTool.updateConfig("cardviewer_game_x", evt.getComponent().getX());
            FTool.updateConfig("cardviewer_game_y", evt.getComponent().getY());
        }
    }//GEN-LAST:event_formComponentMoved

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _icon;
    // End of variables declaration//GEN-END:variables
}
