/*
 * CardList.java
 *
 * Created on 2007/2/3 1:03
 */
package org.sais.fantasyfesta.ui;

import javax.swing.*;
import java.util.Collection;
import org.sais.fantasyfesta.card.CardInfo;
import org.sais.fantasyfesta.tool.FTool;
import org.sais.fantasyfesta.card.cardlabel.UniLabel;
import org.sais.fantasyfesta.card.CardDatabase;

/**
 *
 * @author  Romulus
 */
public class CardList extends javax.swing.JFrame {

    /** Creates new form CardList */
    public CardList() throws Exception {
        initComponents();
        CardDatabase.readCardBase();
        loadList();
        cnum.requestFocus();
    }

    private void loadList() {
        DefaultListModel mod = new DefaultListModel();
        Collection<CardInfo> cards = CardDatabase.listCards();
        ListItem[] litem = new ListItem[cards.size()];
        mod.removeAllElements();
        int i = 0;
        for (CardInfo info : cards) {
            litem[i] = new ListItem(info.getBackgroundColor(), info.getName(), new UniLabel(null, info.createCard()));
            mod.addElement(litem[i]);
            ++i;
        }
        clist.setModel(mod);
        clist.setCellRenderer(new MyCellRenderer());
        clist.addMouseListener(new java.awt.event.MouseAdapter() {

            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int index = clist.locationToIndex(evt.getPoint());
                FTool.showCard(((ListItem) (clist.getModel().getElementAt(index))).label.getInfo(), SCArea);
            }

            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                if (moveandshow.isSelected()) {
                    int index = clist.locationToIndex(evt.getPoint());
                    FTool.showCard(((ListItem) (clist.getModel().getElementAt(index))).label.getInfo(), SCArea);
                }
            }
        });
        clist.addMouseMotionListener(new java.awt.event.MouseAdapter() {

            @Override
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                if (moveandshow.isSelected()) {
                    int index = clist.locationToIndex(evt.getPoint());
                    FTool.showCard(((ListItem) (clist.getModel().getElementAt(index))).label.getInfo(), SCArea);
                }
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        clist = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        SCArea = new javax.swing.JTextPane();
        moveandshow = new javax.swing.JCheckBox();
        cnum = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fantasy Festa CardList");

        clist.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        clist.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                clistValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(clist);

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        SCArea.setFont(new java.awt.Font(java.util.ResourceBundle.getBundle("MainFrame").getString("txtfield.font"), 0, 12));
        SCArea.setPreferredSize(new java.awt.Dimension(400, 580));
        jScrollPane3.setViewportView(SCArea);

        moveandshow.setText("Move and Show");
        moveandshow.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        moveandshow.setMargin(new java.awt.Insets(0, 0, 0, 0));

        cnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnumActionPerformed(evt);
            }
        });

        jLabel1.setText("Card #");

        cname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnameActionPerformed(evt);
            }
        });

        jLabel2.setText("Cardname");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moveandshow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cnum, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(cnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moveandshow))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void cnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnameActionPerformed
       try {
           for (int i = 0; i < 2000; ++i) {
               if (((ListItem) (clist.getModel().getElementAt(i))).label.getInfo().getName().contains(cname.getText())) {
                   clist.setSelectedIndex(i);
                   clist.ensureIndexIsVisible(i);
                   break;
               }
           }
       } catch (ArrayIndexOutOfBoundsException ex) {
           ex.printStackTrace();
           JOptionPane.showMessageDialog(this, "No Such Card!");
       }
       cname.setSelectionStart(0);
       cname.setSelectionEnd(cname.getText().length());
   }//GEN-LAST:event_cnameActionPerformed

   private void cnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnumActionPerformed
       if (cnum.getText().toLowerCase().startsWith("v0")) {
           cnum.setText("99" + cnum.getText().substring(2));
       }
       try {
           for (int i = 0; i < 2000; ++i) {
               if (((ListItem) (clist.getModel().getElementAt(i))).label.getInfo().isNo(FTool.safeParseInt(cnum.getText()))) {
                   clist.setSelectedIndex(i);
                   clist.ensureIndexIsVisible(i);
                   break;
               }
           }
       } catch (ArrayIndexOutOfBoundsException ex) {
           ex.printStackTrace();
           JOptionPane.showMessageDialog(this, "No Such Card!");
       }
       cnum.setSelectionStart(0);
       cnum.setSelectionEnd(4);
   }//GEN-LAST:event_cnumActionPerformed

   private void clistValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_clistValueChanged
       int index = clist.getSelectedIndex();
       FTool.showCard(((ListItem) (clist.getModel().getElementAt(index))).label.getInfo(), SCArea);
   }//GEN-LAST:event_clistValueChanged

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.setVisible(false);
       this.dispose();
   }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane SCArea;
    private javax.swing.JList clist;
    private javax.swing.JTextField cname;
    private javax.swing.JTextField cnum;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JCheckBox moveandshow;
    // End of variables declaration//GEN-END:variables
}
