/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrontFrame.java
 *
 * Created on 2008-12-10, 18:22:16
 */
package org.sais.fantasyfesta.ui;

import java.awt.Container;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.io.*;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Locale;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import org.sais.fantasyfesta.tool.FTool;

/**
 *
 * @author js
 */
public class FrontFrame extends javax.swing.JFrame {

    Container container = getContentPane();
    Locale locales[] = Locale.getAvailableLocales();
    Locale[] defaultLocales = {Locale.getDefault(), Locale.JAPAN, Locale.CHINA, Locale.TAIWAN, new Locale("zh", "HK"), Locale.US};
    Locale locale = Locale.getDefault();
    Locale locale2 = Locale.getDefault();
    HashMap<String, Locale> localeMap;
    boolean semiautoUpdate = true;
    boolean playBGM = false;
    boolean customizedIcon = false;
    boolean externBGMPlayer = false;
    boolean background = false;
    String language = "";
    String country = "";
    String externBGMPlayerPath = "externBGMPlayerPath";
    private String fontname;
    float alpha = 1.0f;

    /** Creates new form FrontFrame */
    public FrontFrame() {
        initModel();
        initComponents();
        if (fontname != null) {
            FTool.setMyFont(this, new Font(fontname, 0, 12));
        } else {
            FTool.setMyFont(this, new Font(java.util.ResourceBundle.getBundle("org/sais/fantasyfesta/ui/Bundle").getString("FrontFrame.default.font"), 0, 12));
        }

    }

    void initModel() {

        if (FTool.readConfig("semiautoupdate") != null) {
            if (FTool.readConfig("semiautoupdate").equals("off")) {
                semiautoUpdate = false;
            } else {
                semiautoUpdate = true;
            }
        }

        if (FTool.readConfig("playbgm") != null) {
            if (FTool.readConfig("playbgm").equals("true")) {
                playBGM = true;
            } else {
                playBGM = false;
            }
        }

        if (FTool.readConfig("background") != null) {
            if (FTool.readConfig("background").equals("true")) {
                background = true;
            } else {
                background = false;
            }
        }


        if (FTool.readConfig("externbgmplayer").equals("true")) {
            externBGMPlayer = true;
        } else {
            externBGMPlayer = false;
        }


        if (FTool.readConfig("externbgmplayerpath") != null) {
            externBGMPlayerPath = FTool.readConfig("externbgmplayerpath");
        }
        if (FTool.readConfig("externbgmplayerpath") != null) {
            fontname = FTool.readConfig("font");

        }
        if (FTool.readConfig("customizedicon") != null) {
            if (FTool.readConfig("customizedicon").equals("true")) {
                customizedIcon = true;
            } else {
                customizedIcon = false;
            }
        }
        if (FTool.readConfig("alpha") != null && !FTool.readConfig("alpha").equals("")) {
            alpha = Float.parseFloat(FTool.readConfig("alpha"));
            if (Float.isNaN(alpha) || alpha > 1.0) {
                alpha = 1.0f;
            }
        }


        language = FTool.readConfig("language");
        country = FTool.readConfig("country");
        if (!((language.equals("")) || (language == null))) {
            locale = new Locale(language, country);
        }
        FTool.setLocale();

        BackgroundManager.loadImagePaths();
        BackgroundManager.loadMusicPaths();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane4 = new javax.swing.JScrollPane();

        String[] defaultLocaleNames = new String[defaultLocales.length];
        for(int i=0;i<defaultLocales.length;i++)
        {
            defaultLocaleNames[i] = defaultLocales[i].getDisplayName();
        }
        defaultLocaleNames[0] = defaultLocales[0].getDisplayName()+"  - Default";

        jList4 = new JList(defaultLocaleNames);
        jList4.setSelectedIndex(0);
        jScrollPane1 = new javax.swing.JScrollPane();
        localeMap  = new HashMap<String,Locale>();
        for(int i = 0;i<locales.length;i++)
        {
            localeMap.put(locales[i].getDisplayName(),locales[i]);
        }
        Object[] localeDisplay = localeMap.keySet().toArray();
        Arrays.sort(localeDisplay);
        jList1 = new JList(localeDisplay);
        updateGeneralButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        fontButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        _bgmlist = new JList(BackgroundManager.listScene().toArray());
        jPanel5 = new javax.swing.JPanel();
        externBGMPlayerField = new javax.swing.JTextField();
        externBGMPlayerField.setText(externBGMPlayerPath);
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        _bgmpath = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        _bgimagelist = new JList(BackgroundManager.listScene().toArray());
        jButton5 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        _bgimagePath = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jSlider1.setValue((int)(alpha*100));
        jLabel1 = new javax.swing.JLabel();
        jImagePanel1 = new org.sais.fantasyfesta.ui.JImagePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/sais/fantasyfesta/ui/Bundle"); // NOI18N
        setTitle(bundle.getString("FrontFrame.title")); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("FrontFrame.jPanel4.border.title"))); // NOI18N

        jCheckBox1.setSelected(semiautoUpdate);
        jCheckBox1.setText(bundle.getString("FrontFrame.jCheckBox1.text")); // NOI18N

        jCheckBox2.setSelected(playBGM);
        jCheckBox2.setText(bundle.getString("FrontFrame.jCheckBox2.text")); // NOI18N

        jCheckBox3.setSelected(customizedIcon);
        jCheckBox3.setText(bundle.getString("FrontFrame.jCheckBox3.text")); // NOI18N

        jCheckBox4.setSelected(background);
        jCheckBox4.setText(bundle.getString("FrontFrame.jCheckBox4.text")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox4))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jCheckBox1)
                .addGap(2, 2, 2)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("FrontFrame.jPanel2.border.title"))); // NOI18N

        jTextField3.setEditable(false);
        jTextField3.setText(locale.getDisplayName());

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setSelected(true);
        jRadioButton2.setText(bundle.getString("FrontFrame.jRadioButton2.text")); // NOI18N

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText(bundle.getString("FrontFrame.jRadioButton3.text")); // NOI18N

        jTextField1.setEditable(false);
        jTextField1.setText(locale2.getDisplayName());

        jList4.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList4ValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(jList4);

        jTabbedPane2.addTab(bundle.getString("FrontFrame.jScrollPane4.TabConstraints.tabTitle"), jScrollPane4); // NOI18N

        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                changeSelectedLocale(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jTabbedPane2.addTab(bundle.getString("FrontFrame.jScrollPane1.TabConstraints.tabTitle"), jScrollPane1); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );

        updateGeneralButton.setText(bundle.getString("FrontFrame.updateGeneralButton.text")); // NOI18N
        updateGeneralButton.setActionCommand(bundle.getString("FrontFrame.updateGeneralButton.actionCommand")); // NOI18N
        updateGeneralButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateGeneralConfig(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        fontButton.setText(bundle.getString("FrontFrame.fontButton.text")); // NOI18N
        fontButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fontButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(fontButton)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(fontButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(updateGeneralButton)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(updateGeneralButton)
                        .addGap(25, 25, 25))))
        );

        jTabbedPane1.addTab(bundle.getString("FrontFrame.jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        _bgmlist.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                _bgmlistValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(_bgmlist);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("FrontFrame.jPanel5.border.title"))); // NOI18N

        jButton1.setText(bundle.getString("FrontFrame.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseBGMPlayer(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(externBGMPlayerField, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(externBGMPlayerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jRadioButton1.setSelected(externBGMPlayer);
        jRadioButton1.setText(bundle.getString("FrontFrame.jRadioButton1.text")); // NOI18N
        jRadioButton1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                externBGMPlayerStateChanged(evt);
            }
        });

        jButton4.setText(bundle.getString("FrontFrame.jButton4.text")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBGM(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButton2.setText(bundle.getString("FrontFrame.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseBGM(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(201, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(12, 12, 12))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(_bgmpath, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(_bgmpath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRadioButton1)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jButton4)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addContainerGap())
        );

        jTabbedPane1.addTab(bundle.getString("FrontFrame.jPanel3.TabConstraints.tabTitle"), jPanel3); // NOI18N

        _bgimagelist.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                _bgimagelistValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(_bgimagelist);

        jButton5.setText(bundle.getString("FrontFrame.jButton5.text")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBackground(evt);
            }
        });

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButton6.setText(bundle.getString("FrontFrame.jButton6.text")); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseBackground(evt);
            }
        });

        jLabel2.setText(bundle.getString("FrontFrame.jLabel2.text")); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(28, 28, 28))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(_bgimagePath, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(_bgimagePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(10, 10, 10))))
        );

        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        jLabel1.setText(String.format("%.2f",alpha)+"f");

        jImagePanel1.setPreferredSize(new java.awt.Dimension(116, 100));

        javax.swing.GroupLayout jImagePanel1Layout = new javax.swing.GroupLayout(jImagePanel1);
        jImagePanel1.setLayout(jImagePanel1Layout);
        jImagePanel1Layout.setHorizontalGroup(
            jImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );
        jImagePanel1Layout.setVerticalGroup(
            jImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addGap(131, 131, 131))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1))
                                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jImagePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addComponent(jImagePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)))
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5)
                        .addGap(7, 7, 7)))
                .addContainerGap())
        );

        jTabbedPane1.addTab(bundle.getString("FrontFrame.jPanel8.TabConstraints.tabTitle"), jPanel8); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeSelectedLocale(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_changeSelectedLocale
        // TODO add your handling code here:


        if (jRadioButton2.isSelected()) {
            locale = localeMap.get(jList1.getSelectedValue());
            jTextField3.setText(locale.getDisplayName());
        } else if (jRadioButton3.isSelected()) {
            locale2 = localeMap.get(jList1.getSelectedValue());
            jTextField1.setText(locale2.getDisplayName());
        }

    }//GEN-LAST:event_changeSelectedLocale

    private void updateGeneralConfig(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateGeneralConfig
        // TODO add your handling code here:
        if (jCheckBox1.isSelected()) {
            FTool.updateConfig("semiautoupdate", "on");
        } else {
            FTool.updateConfig("semiautoupdate", "off");
        }

        if (jCheckBox2.isSelected()) {
            FTool.updateConfig("playbgm", "true");
        } else {
            FTool.updateConfig("playbgm", "false");
        }

        if (jCheckBox3.isSelected()) {
            FTool.updateConfig("customizedicon", "true");
        } else {
            FTool.updateConfig("customizedicon", "false");
        }
        if (jCheckBox4.isSelected()) {
            FTool.updateConfig("background", "true");
        } else {
            FTool.updateConfig("background", "false");
        }

        FTool.updateConfig("language", locale.getLanguage());
        FTool.updateConfig("country", locale.getCountry());
        //   Locale.setDefault(locale);
        FTool.updateConfig("carddatalanguage", locale2.getLanguage());
        FTool.updateConfig("carddatacountry", locale2.getCountry());
        FTool.updateConfig("font", fontname);


    }//GEN-LAST:event_updateGeneralConfig

    private void chooseBGMPlayer(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseBGMPlayer
        // TODO add your handling code here:
        File file = new File(externBGMPlayerField.getText());
        if (file.exists()) {
            jFileChooser1.setCurrentDirectory(file);
        }
        int result = jFileChooser1.showOpenDialog(null);
        if (result == JFileChooser.CANCEL_OPTION) {
            return;
        }

        externBGMPlayerField.setText(jFileChooser1.getSelectedFile().getPath());


    }//GEN-LAST:event_chooseBGMPlayer

    private void _bgmlistValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event__bgmlistValueChanged
        _bgmpath.setText((String) _bgmlist.getSelectedValue());
    }//GEN-LAST:event__bgmlistValueChanged

    private void ChooseBGM(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseBGM
        // TODO add your handling code here:
        File file = new File(_bgmpath.getText());
        if (file.exists()) {
            jFileChooser1.setCurrentDirectory(file);
        }
        int result = jFileChooser1.showOpenDialog(null);
        if (result == JFileChooser.CANCEL_OPTION) {
            return;
        }

        _bgmpath.setText(jFileChooser1.getSelectedFile().getPath());
}//GEN-LAST:event_ChooseBGM

    private void updateBGM(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBGM
        if (externBGMPlayer) {
            FTool.updateConfig("externbgmplayer", "true");
            FTool.updateConfig("externbgmplayerpath", externBGMPlayerField.getText());
        } else {
            FTool.updateConfig("externbgmplayer", "false");
        }
        BackgroundManager.setMusicPath((String) _bgmlist.getSelectedValue(), _bgmpath.getText());
        BackgroundManager.writeMusicPaths();
    }//GEN-LAST:event_updateBGM

    private void externBGMPlayerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_externBGMPlayerStateChanged
        // TODO add your handling code here:
        externBGMPlayer = jRadioButton1.isSelected();
    }//GEN-LAST:event_externBGMPlayerStateChanged

    private void fontButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fontButtonActionPerformed
        // TODO add your handling code here:
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();

        JList fontNames = new JList(ge.getAvailableFontFamilyNames());

        int response = JOptionPane.showConfirmDialog(this, new JScrollPane(fontNames));
        Font font = new Font(fontNames.getSelectedValue().toString(), 0, 12);
        if (response == JOptionPane.YES_OPTION && font != null) {
            System.out.println(font);
            FTool.setMyFont(container, font);
            fontname = font.getName();
        }
    }//GEN-LAST:event_fontButtonActionPerformed

    private void jList4ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList4ValueChanged
        // TODO add your handling code here:
        if (jRadioButton2.isSelected()) {
            locale = defaultLocales[jList4.getSelectedIndex()];
            jTextField3.setText(locale.getDisplayName());
        } else if (jRadioButton3.isSelected()) {
            locale2 = defaultLocales[jList4.getSelectedIndex()];
            jTextField1.setText(locale2.getDisplayName());
        }
    }//GEN-LAST:event_jList4ValueChanged

    private void _bgimagelistValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event__bgimagelistValueChanged
        _bgimagePath.setText(BackgroundManager.getImagePath((String) _bgimagelist.getSelectedValue()));
        jImagePanel1.setImage(_bgimagePath.getText());
        jImagePanel1.repaint();
    }//GEN-LAST:event__bgimagelistValueChanged

    private void ChooseBackground(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseBackground
        File file = new File(_bgimagePath.getText());
        if (file.exists()) {
            jFileChooser1.setCurrentDirectory(file);
        }
        int result = jFileChooser1.showOpenDialog(null);
        if (result == JFileChooser.CANCEL_OPTION) {
            return;
        }

        _bgimagePath.setText(jFileChooser1.getSelectedFile().getPath());
        jImagePanel1.setImage(jFileChooser1.getSelectedFile().getPath());
        jImagePanel1.repaint();
}//GEN-LAST:event_ChooseBackground

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        // TODO add your handling code here:
        alpha = (float) jSlider1.getValue() / 100f;
        jLabel1.setText(String.format("%.2f", alpha) + "f");
        jImagePanel1.setAlpha(alpha);
        jImagePanel1.repaint();
    }//GEN-LAST:event_jSlider1StateChanged

private void updateBackground(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBackground
    BackgroundManager.setImagePath((String) (_bgimagelist.getSelectedValue()), _bgimagePath.getText());
    BackgroundManager.writeImagePaths();
    FTool.updateConfig("alpha", String.format("%.2f", alpha));
    JOptionPane.showMessageDialog(this, "Saved.");
}//GEN-LAST:event_updateBackground

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrontFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField _bgimagePath;
    private javax.swing.JList _bgimagelist;
    private javax.swing.JList _bgmlist;
    private javax.swing.JTextField _bgmpath;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField externBGMPlayerField;
    private javax.swing.JButton fontButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JFileChooser jFileChooser1;
    private org.sais.fantasyfesta.ui.JImagePanel jImagePanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JList jList4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton updateGeneralButton;
    // End of variables declaration//GEN-END:variables
}
