/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrontFrame.java
 *
 * Created on 2008-12-10, 18:22:16
 */
package fantasyfestafront;

import java.awt.Component;
import java.awt.Container;
import java.awt.Font;
import java.io.*;
import java.lang.String;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Locale;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.ListModel;
import javax.swing.UIManager;

/**
 *
 * @author js
 */
public class FrontFrame extends javax.swing.JFrame {

    Locale locales[] = Locale.getAvailableLocales();
    Locale locale = Locale.getDefault();
    HashMap<String, Locale> localeMap;
    boolean semiautoUpdate = true;
    boolean playBGM = false;
    boolean customizedIcon = false;
    boolean externBGMPlayer = false;
    String language = "";
    String country = "";
    String externBGMPlayerPath = "externBGMPlayerPath";
    ArrayList<String> sceneName = new ArrayList<String>();
    ArrayList<String> BGMPath = new ArrayList<String>();
    private Object Comp;

    /** Creates new form FrontFrame */
    public FrontFrame() {
        initModel();
        initComponents();
        setMyFont(this);
    }

    void initModel() {

        if (Tools.readConfig("semiautoupdate").equals("on")) {
            semiautoUpdate = true;
        } else {
            semiautoUpdate = false;
        }

        if (Tools.readConfig("playbgm").equals("true")) {
            playBGM = true;
        } else {
            playBGM = false;
        }
        if (Tools.readConfig("externbgmplayer").equals("true")) {
           
            externBGMPlayer = true;
        } else {
            externBGMPlayer = false;
        }

        if (Tools.readConfig("externbgmplayerpath") != null) {
            externBGMPlayerPath = Tools.readConfig("externbgmplayerpath");
        }

        if (Tools.readConfig("customizedicon").equals("true")) {
            customizedIcon = true;
        } else {
            customizedIcon = false;
        }

        language = Tools.readConfig("language");
        country = Tools.readConfig("country");
        if (!((language.equals("")) || (language == null))) {


            locale = new Locale(language, country);

        }

        Tools.loadBGM(sceneName, BGMPath);


    }

    private void setMyFont(Component Comp) {
        Font myFont = new Font(java.util.ResourceBundle.getBundle("fantasyfestafront/Bundle").getString("FrontFrame.default.font"), Font.PLAIN, 12);
        if (Comp != null) {
            try {
                Comp.setFont(myFont);
            } catch (Exception e) {
                return;
            }
        }
        if (Comp instanceof Container) {
            Component[] components = ((Container) Comp).getComponents();
            for (int i = 0; i < components.length; i++) {
                Component child = components[i];
                if (child != null) {
                    //System.out.println(child.getClass().getName());
                    setMyFont(child);
                }
            }
        }
        return;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new JList(BGMPath.toArray());
        jFileChooser1 = new javax.swing.JFileChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        localeMap  = new HashMap<String,Locale>();
        for(int i = 0;i<locales.length;i++)
        {
            localeMap.put(locales[i].getDisplayName(),locales[i]);
        }
        Object[] localeDisplay = localeMap.keySet().toArray();
        Arrays.sort(localeDisplay);
        jList1 = new JList(localeDisplay);
        jTextField3 = new javax.swing.JTextField();
        updateGeneralButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new JList(sceneName.toArray());
        jPanel5 = new javax.swing.JPanel();
        externBGMPlayerField = new javax.swing.JTextField();
        externBGMPlayerField.setText(externBGMPlayerPath);
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        BGMPathField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        changeButton = new javax.swing.JButton();

        jScrollPane3.setViewportView(jList3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(java.util.ResourceBundle.getBundle("fantasyfestafront/Bundle").getString("FrontFrame.title")+" " +java.util.ResourceBundle.getBundle("fantasyfestafront/Bundle").getString("FrontFrame.version"));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("fantasyfestafront/Bundle"); // NOI18N
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("FrontFrame.jPanel4.border.title"))); // NOI18N

        jCheckBox1.setSelected(semiautoUpdate);
        jCheckBox1.setText(bundle.getString("FrontFrame.jCheckBox1.text")); // NOI18N

        jCheckBox2.setSelected(playBGM);
        jCheckBox2.setText(bundle.getString("FrontFrame.jCheckBox2.text")); // NOI18N

        jCheckBox3.setSelected(customizedIcon);
        jCheckBox3.setText(bundle.getString("FrontFrame.jCheckBox3.text")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jCheckBox1)
                .addGap(2, 2, 2)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox3)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("FrontFrame.jPanel2.border.title"))); // NOI18N

        jLabel3.setText(bundle.getString("FrontFrame.jLabel3.text")); // NOI18N

        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                changeSelectedLocale(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jTextField3.setText(locale.getDisplayName());
        jTextField3.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(16, 16, 16)
                        .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        updateGeneralButton.setText(bundle.getString("FrontFrame.updateGeneralButton.text")); // NOI18N
        updateGeneralButton.setActionCommand(bundle.getString("FrontFrame.updateGeneralButton.actionCommand")); // NOI18N
        updateGeneralButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateGeneralConfig(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(updateGeneralButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(updateGeneralButton)
                        .addGap(51, 51, 51))))
        );

        jTabbedPane1.addTab(bundle.getString("FrontFrame.jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        jList2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList2ValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("FrontFrame.jPanel5.border.title"))); // NOI18N

        jButton1.setText(bundle.getString("FrontFrame.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseBGMPlayer(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(externBGMPlayerField, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap(193, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(externBGMPlayerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jRadioButton1.setSelected(externBGMPlayer);
        jRadioButton1.setText(bundle.getString("FrontFrame.jRadioButton1.text")); // NOI18N
        jRadioButton1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                externBGMPlayerStateChanged(evt);
            }
        });

        jButton4.setText(bundle.getString("FrontFrame.jButton4.text")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBGM(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButton2.setText(bundle.getString("FrontFrame.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseBGM(evt);
            }
        });

        changeButton.setText(bundle.getString("FrontFrame.changeButton.text")); // NOI18N
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeBGMPath(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BGMPathField, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap(92, Short.MAX_VALUE)
                        .addComponent(changeButton)
                        .addGap(32, 32, 32)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(BGMPathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(changeButton)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRadioButton1)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jButton4)))
                .addGap(17, 17, 17))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addContainerGap())
        );

        jTabbedPane1.addTab(bundle.getString("FrontFrame.jPanel3.TabConstraints.tabTitle"), jPanel3); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeSelectedLocale(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_changeSelectedLocale
        // TODO add your handling code here:

        locale = localeMap.get(jList1.getSelectedValue());
        jTextField3.setText(locale.getDisplayName());
    }//GEN-LAST:event_changeSelectedLocale

    private void updateGeneralConfig(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateGeneralConfig
        // TODO add your handling code here:
        if (jCheckBox1.isSelected()) {
            Tools.updateConfig("semiautoupdate", "on");
        } else {
            Tools.updateConfig("semiautoupdate", "off");
        }

        if (jCheckBox2.isSelected()) {
            Tools.updateConfig("playbgm", "true");
        } else {
            Tools.updateConfig("playbgm", "false");
        }

        if (jCheckBox3.isSelected()) {
            Tools.updateConfig("customizedicon", "true");
        } else {
            Tools.updateConfig("customizedicon", "false");
        }

        Tools.updateConfig("language", locale.getLanguage());
        Tools.updateConfig("country", locale.getCountry());
    }//GEN-LAST:event_updateGeneralConfig

    private void chooseBGMPlayer(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseBGMPlayer
        // TODO add your handling code here:
        File file = new File(externBGMPlayerField.getText());
        if (file.exists()) {
            jFileChooser1.setCurrentDirectory(file);
        }
        int result = jFileChooser1.showOpenDialog(null);
        if (result == JFileChooser.CANCEL_OPTION) {
            return;
        }

        externBGMPlayerField.setText(jFileChooser1.getSelectedFile().getPath());


    }//GEN-LAST:event_chooseBGMPlayer

    private void jList2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList2ValueChanged
        // TODO add your handling code here:
        BGMPathField.setText(BGMPath.get(jList2.getSelectedIndex()));
    }//GEN-LAST:event_jList2ValueChanged

    private void ChooseBGM(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseBGM
        // TODO add your handling code here:
        File file = new File(BGMPathField.getText());
        if (file.exists()) {
            jFileChooser1.setCurrentDirectory(file);
        }
        int result = jFileChooser1.showOpenDialog(null);
        if (result == JFileChooser.CANCEL_OPTION) {
            return;
        }

        BGMPathField.setText(jFileChooser1.getSelectedFile().getPath());
}//GEN-LAST:event_ChooseBGM

    private void changeBGMPath(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeBGMPath
        // TODO add your handling code here:
       try
       {
        BGMPath.set(jList2.getSelectedIndex(), BGMPathField.getText());
       }
       catch(ArrayIndexOutOfBoundsException e)
       {

       }
}//GEN-LAST:event_changeBGMPath

    private void updateBGM(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBGM
        // TODO add your handling code here:
        if (externBGMPlayer) {
            Tools.updateConfig("externbgmplayer", "true");
            Tools.updateConfig("externbgmplayerpath", externBGMPlayerField.getText());
        } else {
            Tools.updateConfig("externbgmplayer", "false");
        }
        Tools.updateBGM(sceneName, BGMPath);
    }//GEN-LAST:event_updateBGM

    private void externBGMPlayerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_externBGMPlayerStateChanged
        // TODO add your handling code here:
        externBGMPlayer = jRadioButton1.isSelected();
    }//GEN-LAST:event_externBGMPlayerStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrontFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BGMPathField;
    private javax.swing.JButton changeButton;
    private javax.swing.JTextField externBGMPlayerField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JList jList3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton updateGeneralButton;
    // End of variables declaration//GEN-END:variables
}
