/*
 * ProxyMainFrame.java
 *
 * Created on 2007/09/23, 20:26
 */
package org.sais.fantasyfestaproxy;

import java.awt.Color;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ImageIcon;
import javax.swing.text.Document;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;

/**
 *
 * @author  Romulus
 */
public class ProxyMainFrame extends javax.swing.JFrame {

    public ProxyServer mServer;
    public boolean mExitOnDispose = true;

    public static ProxyMainFrame autoLaunch() {
        ProxyMainFrame main = new ProxyMainFrame(false);
        main.setVisible(true);
        main.active();
        return main;
    }
    
    public static ProxyMainFrame autoLaunch(boolean grade) {
        ProxyMainFrame main = new ProxyMainFrame(false);
        main.setVisible(true);
        main.active(grade);
        return main;
    }

    public ProxyMainFrame(boolean exitOnDispose) {
        initComponents();
        mExitOnDispose = exitOnDispose;
        /*    try {
        System.setOut(new PrintStream(new FileOutputStream("message_proxy.log")));
        System.setErr(new PrintStream(new FileOutputStream("message_error.log")));
        } catch (FileNotFoundException ex) {
        ex.printStackTrace();
        }*/
        Timer timeout = new Timer();
        timeout.schedule(new TimerTask() {

            @Override
            public void run() {
                dispose();
            }
        }, 432000000); // 5 hours timeout
        setIconImage(new ImageIcon(getClass().getResource("/icon.JPG")).getImage());
        this.setLocation(70, 70);
    }

    public int[] getPorts() {
        return new int[]{Integer.parseInt(_vhostport.getText()),
                    Integer.parseInt(_vclientport.getText()),
                    Integer.parseInt(_watcherport.getText())};
    }

    public void insertMessage(String message, Color color) {
        try {
            SimpleAttributeSet set = new SimpleAttributeSet();
            Document doc = Messagebox.getStyledDocument();
            StyleConstants.setForeground(set, color);
            doc.insertString(doc.getLength(), message + '\n', set);
            Messagebox.setCaretPosition(Messagebox.getDocument().getLength() - 1);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void active() {
        active(false);
    }
    
    private void active(boolean grade) {
        mServer = new ProxyServer(this, Integer.parseInt(_vhostport.getText()),
                Integer.parseInt(_vclientport.getText()),
                Integer.parseInt(_watcherport.getText()),
                grade);
        _vhoststate.setText("Waiting...");
        _vclientstate.setText("Waiting...");
        _active.setEnabled(false);
    }

    public void setVHostState(String state) {
        _vhoststate.setText(state);
        checkShutDown();
    }

    public void setVClientState(String state) {
        _vclientstate.setText(state);
        checkShutDown();
    }

    private void checkShutDown() {
        if (_vclientstate.getText().equals("Disconnected.") && _vhoststate.getText().equals("Disconnected.")) {
            dispose();
        }
    }

    public void setWatcherState(String state) {
        _watcherstate.setText(state);
    }

    public void setVHostPort(int port) {
        _vhostport.setText(String.valueOf(port));
    }

    public void setVClientPort(int port) {
        _vclientport.setText(String.valueOf(port));
    }

    public void setWatcherPort(int port) {
        _watcherport.setText(String.valueOf(port));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        _vhostport = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        _vclientport = new javax.swing.JTextField();
        _vhoststate = new javax.swing.JLabel();
        _vclientstate = new javax.swing.JLabel();
        _exit = new javax.swing.JButton();
        _active = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        _watcherport = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Messagebox = new javax.swing.JTextPane();
        _watcherstate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FFO Proxy AKIRA 2nd degree");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel1.setText("Virtual Host: Port");

        _vhostport.setFont(new java.awt.Font("Times New Roman", 0, 14));
        _vhostport.setText("12701");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel2.setText("Virtual Client: Port");

        _vclientport.setFont(new java.awt.Font("Times New Roman", 0, 14));
        _vclientport.setText("12702");

        _vhoststate.setFont(new java.awt.Font("Times New Roman", 0, 14));
        _vhoststate.setText("Stanby.");

        _vclientstate.setFont(new java.awt.Font("Times New Roman", 0, 14));
        _vclientstate.setText("Stanby.");

        _exit.setText("Exit");
        _exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _exitActionPerformed(evt);
            }
        });

        _active.setText("Active Proxy");
        _active.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _activeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel3.setText("Watchers: Port");

        _watcherport.setFont(new java.awt.Font("Times New Roman", 0, 14));
        _watcherport.setText("12703");

        Messagebox.setFont(new java.awt.Font("ＭＳ Ｐゴシック", 0, 12)); // NOI18N
        jScrollPane2.setViewportView(Messagebox);

        _watcherstate.setFont(new java.awt.Font("Times New Roman", 0, 14));
        _watcherstate.setText("0 watchers.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(_active))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(_watcherport)
                    .addComponent(_vclientport)
                    .addComponent(_vhostport, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_watcherstate)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(_vhoststate)
                        .addComponent(_vclientstate))
                    .addComponent(_exit))
                .addContainerGap(146, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(_vhoststate)
                    .addComponent(_vhostport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(_vclientstate)
                    .addComponent(_vclientport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(_watcherport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_watcherstate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_active)
                    .addComponent(_exit))
                .addContainerGap(282, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(158, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void _activeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__activeActionPerformed
      active();
  }//GEN-LAST:event__activeActionPerformed

  private void _exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__exitActionPerformed
      if (mServer != null) {
        mServer.close();
      }
      this.dispose();
  }//GEN-LAST:event__exitActionPerformed

  private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
      if (mServer != null) {
        mServer.close();
      }
      if (mExitOnDispose) {
          System.exit(0);
      }
  }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        if (args.length > 0) {
            if (args[0].equals("auto")) {
                ProxyMainFrame main = new ProxyMainFrame(true);
                main.setVisible(true);
                main.active();
            }
            return;
        }
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new ProxyMainFrame(true).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane Messagebox;
    private javax.swing.JButton _active;
    private javax.swing.JButton _exit;
    private javax.swing.JTextField _vclientport;
    private javax.swing.JLabel _vclientstate;
    private javax.swing.JTextField _vhostport;
    private javax.swing.JLabel _vhoststate;
    private javax.swing.JTextField _watcherport;
    private javax.swing.JLabel _watcherstate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
